export const INDUSTRY_OPTIONS = [
  { label: "Advertising & Marketing", value: "Advertising & Marketing" },
  { label: "Agriculture", value: "Agriculture" },
  { label: "Automotive", value: "Automotive" },
  { label: "Construction", value: "Construction" },
  { label: "Education", value: "Education" },
  { label: "Energy & Utilities", value: "Energy & Utilities" },
  { label: "Financial Services", value: "Financial Services" },
  { label: "Food & Beverage", value: "Food & Beverage" },
  { label: "Healthcare", value: "Healthcare" },
  { label: "Hospitality & Travel", value: "Hospitality & Travel" },
  { label: "Legal Services", value: "Legal Services" },
  { label: "Manufacturing", value: "Manufacturing" },
  { label: "Media & Entertainment", value: "Media & Entertainment" },
  { label: "Nonprofit", value: "Nonprofit" },
  { label: "Professional Services", value: "Professional Services" },
  { label: "Real Estate", value: "Real Estate" },
  { label: "Retail & E-commerce", value: "Retail & E-commerce" },
  { label: "Software & Technology", value: "Software & Technology" },
  { label: "Telecommunications", value: "Telecommunications" },
  { label: "Transportation & Logistics", value: "Transportation & Logistics" },
  { label: "Other", value: "Other" },
];

export const MONTHLY_BUDGET_OPTIONS = [
  { label: "$0 - $500 / month", value: "0-500" },
  { label: "$500 - $1,000 / month", value: "500-1000" },
  { label: "$1,000 - $5,000 / month", value: "1000-5000" },
  { label: "$5,000 - $10,000 / month", value: "5000-10000" },
  { label: "$10,000+ / month", value: "10000+" },
];
